Repository MUMU-For-Youth/MUMU_Frontend, pull requests merged in 2025-05, with the labels that each got.

#26 [feat] server api setting
  .gitignore
  package-lock.json
  package.json
  src/api/api.tsx
  src/store/useAuthStore.ts
Labels: feat

#31 [feat] Button 분리(GotoDetail, GotoApply)
  src/components/Button/GotoApplyButton.tsx
  src/components/Button/GotoDetailButton.tsx
  src/components/Button/index.tsx
  src/components/Card.tsx
  src/styles/common.ts
Labels: feat, refactoring

#32 [feat] GotoDetailButton 기능 추가 후 Detail Page 생성
  src/App.tsx
  src/assets/icons/MapIcon.svg
  src/components/Button/GotoDetailButton.tsx
  src/components/Button/GotoMapButton.tsx
  src/components/Button/index.tsx
  src/components/Card.tsx
  src/components/Detail/EducationDetail.tsx
  src/components/Detail/SpaceDetail.tsx
  src/pages/Detail.tsx
  src/routes/AppRoutes.tsx
  src/types/responses.ts
Labels: feat

#34 [feat] 무료 교육/무료 공간 API 연동
  .gitignore
  package-lock.json
  src/components/Button/BookMarkIconButton.tsx
  src/components/Card.tsx
  src/components/SpaceTextSection.tsx
  src/pages/EducationList.tsx
  src/pages/Mypage.tsx
  src/pages/SpaceList.tsx
Labels: feat, refactoring

#35 [feat] flitering component
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownContainer.tsx
  src/components/Dropdown/EduDropdown.tsx
  src/components/Dropdown/SpaceDropdown.tsx
  src/pages/EducationMap.tsx
  src/pages/SpaceMap.tsx
  src/store/useEduFilterStore.ts
  src/store/useSpaceFilterStore.ts
  src/types/filters.tsx
Labels: feat

#37 [feat] 마커 클릭 시 해당 카드로 이동
  src/components/Button/GotoDetailButton.tsx
  src/components/Button/GotoMapButton.tsx
  src/components/NaverMap.tsx
  src/global.d.ts
  src/pages/EducationMap.tsx
  src/pages/SpaceMap.tsx
Labels: feat

#39 [feat] logo 추가
  public/favicon.ico
  public/index.html
  src/assets/logo/Logo.svg
  src/assets/logo/LogoWithText.svg
  src/components/Navigation.tsx
  src/pages/SignUp.tsx
Labels: feat

#43 [feat] kakao sign up
  src/App.tsx
  src/components/Button/BookMarkIconButton.tsx
  src/components/Card.tsx
  src/pages/KakaoCallback.tsx
  src/pages/Mypage.tsx
  src/pages/SignUp.tsx
  src/routes/AppRoutes.tsx
  src/store/useAuthStore.ts
Labels: feat

#45 [feat] member function
  src/App.tsx
  src/api/api.tsx
  src/components/Button/GotoMapButton.tsx
  src/components/Card.tsx
  src/components/Detail/EducationDetail.tsx
  src/components/Detail/SpaceDetail.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownContainer.tsx
  src/components/Dropdown/FilterResetOnRouteChange.tsx
  src/components/Dropdown/SelectedFilteresEducation.tsx
  src/components/Dropdown/SelectedFilteresSpace.tsx
  src/components/EducationTextSection.tsx
  src/components/Navigation.tsx
  src/components/SlidingPanel/DesktopSlidingPanel.tsx
  src/components/SlidingPanel/MobileSlidingPanel.tsx
  src/components/SlidingPanel/index.tsx
  src/components/SlidingTopBar.tsx
  src/components/SpaceTextSection.tsx
  src/pages/Detail.tsx
  src/pages/EducationList.tsx
  src/pages/EducationMap.tsx
  src/pages/KakaoCallback.tsx
  src/pages/Mypage.tsx
  src/pages/SignUp.tsx
  src/pages/SpaceList.tsx
  src/pages/SpaceMap.tsx
  src/store/useAuthStore.ts
  src/utils/auth.ts
Labels: feat, fix, refactoring
